name: attendance_app
description: "A new Flutter module project."
version: 1.0.2

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pigment: ^1.0.4
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  google_sign_in: ^6.2.1
  logger: ^2.4.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  intl: ^0.18.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  module:
    androidX: true
    androidPackage: com.example.attendance_app
    iosBundleIdentifier: com.example.attendanceApp
